defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: mike
  password:

production:
  <<: *defaults

test:
  database: conversion_roulette_test
  <<: *defaults

development:
  database: conversion_roulette_development
  <<: *defaults
